language: node_js

branches:
  only:
  - master

jobs:
  include:
    - stage: release
      node_js: "10"
      script: skip # Skip running "yarn test" again
      deploy:
        provider: script
        skip_cleanup: true
        script: yarn run multi-semantic-release